# This workflow will release a package at npmjs and at GitHub releases

name: Release

on:
  push:
    tags:
      - v*

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: BARTOC.org ${{ github.ref }}
        body: TODO
        draft: true
        prerelease: false
